name: SYNC GAMES


on:
  schedule:
    - cron: '0 0 */3 * *'  # Runs at 2:00 AM UTC on Sunday to Thursday
  workflow_dispatch:
    inputs:
      suite-file:
        description: 'SYNC GAMES'
        required: true
        default: SYNC.xml

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: jamesonstone/runner-workspace-cleaner@v1.0.0

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          clean: 'true'

      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: CSXGIT/github-actions
          token: ${{ secrets.GITOPS_SA_PAT }}
          path: .github/actions

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

#      - name: Verify ALPHA.xml Content
#        run: cat src/testng-suites/ALPHA.xml

      - name: Clean target directory
        run: sudo rm -rf target || true

      - name: Run Test
        if: always()
        run: |
          export BUILD_NUMBER=${{ github.run_number }}
          export BUILD_USER=${{ github.actor }}
          suite_file=SYNC.xml
          test_set=$(basename $suite_file .xml)
          mvn clean test --file pom.xml -DTEST_SET=$test_set -DsuiteXmlFile=src/testng-suites/$suite_file
        continue-on-error: true