name: GAME SYNC TO APP

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # בוחר את ספק ה־JDK
          java-version: '11'

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver


      - name: Run SyncGamesForApplication
        run: mvn compile exec:java -Dexec.mainClass="org.example.SyncGamesForApplication"
